### ISSUE TITLE
Build/deploy not working

### ISSUE THREAD

**Issue by VRConservation** [opengeos/cookiecutter-pypackage#4]
### Description

Deploy after making changes. Doesn't deploy:
![image](https://github.com/user-attachments/assets/eba1e977-6dfb-422d-b572-f928e91c3f20)
repo is here: https://github.com/VRConservation/propo

Thanks for any help!

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
You need to add ipyleaflet to requirements.txt.

![image](https://github.com/user-attachments/assets/e7e88979-8f3f-460c-ba78-b2f6908935e9)

**Comment by VRConservation** [comment]
I'm having the same issue in other cookie cutter builds I've added. The propo one is the only that initially worked and set up everything correctly with pypi and the page build. None of the other repos/builds worked.

**Comment by VRConservation** [comment]
Thanks Qiusheng. I only changed that in the yml files after finding a suggested change in your class from last spring (week 9). It was in hopes of fixing the deploy issue. I've looked at the error messages and searched online and with copilot to fix it, but haven't come up with anything. Looks like that made it wors.
